#!/bin/sh

source $HOME/.config/bspwm/colors/nord.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0


bspc config border_width            2
bspc config window_gap              10

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_follows_focus   false
bspc config focus_follows_pointer   true

bspc rule -a TelegramDesktop desktop='^1'

bspc rule -a firefox desktop='^2'

bspc rule -a Steam desktop='^6'
bspc rule -a steam desktop='^6'
bspc rule -a steamwebhelper desktop='^6'
bspc rule -a "SDL Application" desktop='^6'

bspc rule -a Gimp-2.10 desktop='^8'
bspc rule -a Blender desktop='^8'

bspc rule -a vesktop desktop='^9'

bspc rule -a qBittorrent desktop='^10'

bspc rule -a TelegramDesktop state=floating
bspc rule -a *:*:Picture-in-Picture follow=false state=floating sticky=on


# Border
bspc config focused_border_color $FOCUSED_BORDER
bspc config normal_border_color  $NORMAL_BORDER
bspc config active_border_color  $ACTIVE_BORDER


#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Picom
picom -b

# start daemon for virtual audio cables
# systemctl --user is-active --quiet virtual-audio-cables.service || systemctl --user start virtual-audio-cables.service

# Layout
setxkbmap -option grp:caps_toggle us,ru,by &

# Notifications
killall -q dunst
dunst -config "$DUNST_THEME" &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
systemctl --user is-active --quiet wallpaper-changer.service || systemctl --user start wallpaper-changer.service

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Polybar
killall -q polybar
polybar

