#!/bin/sh

source $HOME/.config/bspwm/themes/latte.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0


bspc config border_width            2
bspc config window_gap              10

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_follows_focus   false
bspc config focus_follows_pointer   true

bspc rule -a TelegramDesktop desktop='^1'

bspc rule -a LibreWolf desktop='^2'

bspc rule -a Steam desktop='^4'
bspc rule -a steam desktop='^4'
bspc rule -a steamwebhelper desktop='^4'
bspc rule -a "SDL Application" desktop='^4'

bspc rule -a Gimp-2.10 desktop='^7'
bspc rule -a Gimp-3.0 desktop='^7'
bspc rule -a Blender desktop='^7'

bspc rule -a vesktop desktop='^8'

bspc rule -a qBittorrent desktop='^9'

bspc rule -a TelegramDesktop state=floating
bspc rule -a *:*:Picture-in-Picture follow=false state=floating sticky=on


# Border
bspc config focused_border_color $FOCUSED_BORDER
bspc config normal_border_color  $NORMAL_BORDER
bspc config active_border_color  $ACTIVE_BORDER


#
# Autostart
#
# Set display from arandr saved script
# sh ~/.screenlayout/monitor.sh &
xset s off -dpms

# Picom
picom -b

# Layout
setxkbmap -option grp:caps_toggle us,ru &

# Notifications
killall -q dunst
dunst -config "$DUNST_THEME" &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
~/.config/scripts/wallpapers/wallpaper_changer.sh

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Polybar
killall -q polybar
polybar

