[colors.bright]
black   = "#4c4f69"
blue    = "#1e66f5"
cyan    = "#179299"
green   = "#40a02b"
magenta = "#ea76cb"
red     = "#d20f39"
white   = "#c6d0f5"
yellow  = "#df8e1d"

[colors.normal]
black   = "#737994"
blue    = "#1e66f5"
cyan    = "#179299"
green   = "#40a02b"
magenta = "#ea76cb"
red     = "#d20f39"
white   = "#eff1f5"
yellow  = "#df8e1d"

[colors.primary]
background = "#eff1f5"
foreground = "#4c4f69"
