[colors.bright]
black   = "#4C566A"
blue    = "#81A1C1"
cyan    = "#8FBCBB"
green   = "#A3BE8C"
magenta = "#B48EAD"
red     = "#BF616A"
white   = "#ECEFF4"
yellow  = "#EBCB8B"

[colors.normal]
black   = "#3B4252"
blue    = "#81A1C1"
cyan    = "#88C0D0"
green   = "#A3BE8C"
magenta = "#B48EAD"
red     = "#BF616A"
white   = "#E5E9F0"
yellow  = "#EBCB8B"

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

[cursor]
thickness = 0.3
blink_timeout = 0

[cursor.style]
blinking = "on"
shape    = "underline"

[env]
LANG     = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM     = "alacritty"

[font]
size = 11.0

[font.bold]
family = "SFMono Nerd Font Mono"
style  = "Bold"

[font.italic]
family = "SFMono Nerd Font Mono"
style  = "Italic"

[font.normal]
family = "SFMono Nerd Font Mono"
style  = "Regular"

[window.padding]
x = 4
y = 4
