[colors.normal]
black   = "#4C4F69"
blue    = "#6189B2"
cyan    = "#81A9A8"
green   = "#8CA378"
magenta = "#B48EAD"
red     = "#BF616A"
white   = "#4C4F69"
yellow  = "#EBCB8B"

[colors.primary]
background = "#ECEFF4"
foreground = "#2E3440"

[cursor]
thickness = 0.3

[cursor.style]
blinking = "off"
shape    = "underline"

[env]
LANG     = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM     = "alacritty"

[font]
size = 11.0

[font.bold]
family = "SFMono Nerd Font Mono"
style  = "Bold"

[font.italic]
family = "SFMono Nerd Font Mono"
style  = "Italic"

[font.normal]
family = "SFMono Nerd Font Mono"
style  = "Regular"

[window.padding]
x = 4
y = 4
