[colors.bright]
black   = "#5C6A72"
blue    = "#3A94C5"
cyan    = "#35A77C"
green   = "#8DA101"
magenta = "#DF69BA"
red     = "#F85552"
white   = "#FDF6E3"
yellow  = "#DFA000"

[colors.normal]
black   = "#5C6A72"
blue    = "#3A94C5"
cyan    = "#35A77C"
green   = "#8DA101"
magenta = "#DF69BA"
red     = "#F85552"
white   = "#FDF6E3"
yellow  = "#DFA000"

[colors.primary]
background = "#FDF6E3"
foreground = "#5C6A72"

[cursor]
thickness = 0.3
blink_timeout = 0

[cursor.style]
blinking = "on"
shape    = "underline"

[env]
LANG     = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM     = "alacritty"

[font]
size = 11.0

[font.bold]
family = "SFMono Nerd Font Mono"
style  = "Bold"

[font.italic]
family = "SFMono Nerd Font Mono"
style  = "Italic"

[font.normal]
family = "SFMono Nerd Font Mono"
style  = "Regular"

[window.padding]
x = 4
y = 4

